Page({
    data:{
        records:[
            {
                legend:'婕拉',
                bunko:'胜利',
                details:'1/1/10',
                time:'2018-12-27'
            },
            {
                legend:'婕拉',
                bunko:'胜利',
                details:'6/1/8',
                time:'2018-12-27'
            },
            {
                legend:'婕拉',
                bunko:'胜利',
                details:'3/4/13',
                time:'2018-12-27'
            },
            {
                legend:'婕拉',
                bunko:'失败',
                details:'3/7/3',
                time:'2018-12-27'
            },
            {
                legend:'娜美',
                bunko:'失败',
                details:'3/7/14',
                time:'2018-12-27'
            },
            {
                legend:'娜美',
                bunko:'胜利',
                details:'2/0/7',
                time:'2018-12-27'
            }
        ]
    }
})